---
title: "Research"
description-meta: "Information, pdfs, and social metrics of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: custom.css
---


<!--Include academic icons or buttons-->
{{< include /files/includes/_academic.qmd >}}

Notes: \* corresponding author; <sup>GS</sup> graduate student advisee; <sup>VS</sup> visiting scholar

## Publications

- Vegard Tørstad, Jonas Nahm, Jon Hovi, Tora Skodvin & Gard Olav Dietrichson (2024) Economic recessions and decarbonisation: analysing green stimulus spending in Canada and the US, New Political Economy, 29:4, 513-531, DOI: 10.1080/13563467.2023.2294744
- Pietro Castelli Gattinara, Gard Olav Dietrichson, Iris Beau Segers, & Tamta Gelashvili (forthcoming). Measuring far-right protest: Procedures, standards and data | In *Protests of the Far Right* Edited by Andrea L. P. Pirro, Caterina Froio, & Pietro Castelli Gattinara. Oxford University Press. 

## Working Papers

- Do Mixed Member Systems create division of labour in the substantive representation of women? Evidence from New Zealand (*unpublished manuscript*)
- Proportional spillover? Mixed member elections and women’s political presence in South Africa, with Aksel Sundström and Stephen Dawson (*under review*). 
- Far From Perfect? A Framework for Measuring Democracy Levels in High-Quality Democracies, with Carl Henrik Knutsen, Martin Søyland, Tore Wig, Elin Haugsgjerd Allern, Jan Erling Klausen, and Sirianne Dahlum (*unpublished manuscript*)
